### ISSUE TITLE
style: UI Breakage When Using the Search Bar

### ISSUE THREAD

**Issue by hossainchisty** [hossainchisty/LeafLine-Client#11]
**Issue Summary:**

When users attempt to search using the search bar feature on our application, the user interface (UI) breaks, leading to a poor user experience. This issue needs immediate attention to ensure our users can search seamlessly and efficiently without encountering any disruptions in the UI.

![image](https://github.com/hossainchisty/LeafLine-Client/assets/62835101/a37a2bde-5e75-4a9f-83ae-eb2a0ceeaf82)

**Steps to Reproduce:**

1. Open the application.
2. Locate the search bar at the top of the interface.
3. Enter a search query and press Enter or tap the search icon.

**Expected Behavior:**

- The application should display search results relevant to the entered query.
- The UI elements, including search bar and search results, should remain intact and responsive.

**Actual Behavior:**

- Upon entering a search query and initiating the search, the UI elements break, causing misalignment, overlapping, or disappearance of essential components.
- Users are unable to view the search results properly due to the distorted UI, impacting their ability to interact effectively with the application.

**Impact:**

- Users are discouraged from using the search feature due to the broken UI, affecting user engagement and satisfaction.
- The broken UI could potentially lead to misunderstandings, misinterpretations, or frustration among users, resulting in a negative impact on user trust and loyalty.

This issue is critical for maintaining a seamless user experience and should be prioritized to ensure our application functions as intended.

**Comment by leonyangela** [comment]
Hi can I work on this? could you please assign me to this issue? thanks

**Comment by Umesh9-prog** [comment]
hi @hossainchisty can u assign this issue to me

**Comment by hossainchisty** [comment]
Hello, @leonyangela Assigned You, Wish you best!

**Comment by leonyangela** [comment]
> Hello, @leonyangela Assigned You, Wish you best!

Thank you!
