### ISSUE TITLE
feat: adding dark-mode 

### ISSUE THREAD

**Issue by VinayBagalakoti** [hossainchisty/LeafLine-Client#16]
It is straining to the eyes while looking at night in light mode, it is better to have a feature to toggle between light and dark modes in the website

**Comment by hossainchisty** [comment]
Hi, @VinayBagalakoti it's great idea! if you went to implement you are welcome!

**Comment by VinayBagalakoti** [comment]
can u assign me to it or is it completed ??? @hossainchisty
